### ISSUE TITLE
Expected `string` for value, got `[object Object]`

### ISSUE THREAD

**Issue by harvey56** [conorhastings/react-syntax-highlighter#131]
Hi,

I'd like to highlight code rendered by another component in the SyntaxHighlighter. The SyntaxHighlighter however seems to only take a String.

Passing my component as a child returns the error as in the title : 
```
<SyntaxHighlighter language='javascript' style={this.state.style} showLineNumbers={true}>
     <MyComponent />
</SyntaxHighlighter>
```
Any suggestion how I can achieve this ?

**Comment by conorhastings** [comment]
I'd need to see the contents of my component, either way I don't think this will work as syntax highlighter only works with string children, if <MyComponent /> is a function that returns a string you can call it as {MyComponent()} otherwise you will need to find another way to generate the string you desire
