### ISSUE TITLE
TSX files of storybook

### ISSUE THREAD

**Issue by kushalmahajan** [conorhastings/react-syntax-highlighter#171]
First of all below line doesn't works referencing the #https://github.com/conorhastings/react-syntax-highlighter/issues/130issue

> import SyntaxHighlighter from 'react-syntax-highlighter/prism';

However, according to your README, I tried using 

```
import { atomDark } from 'react-syntax-highlighter/dist/styles/prism';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
```
Later in my Button.stories.tsx file ( Storybook ) 

```
        const codeString = `<Button primary> Primary </Button>`;

      ...                   <Grid container spacing={24}>
                                    <Grid item sm={12}>
                                        <SyntaxHighlighter language='javascript' style={atomDark}>
                                           {codeString}
                                        </SyntaxHighlighter>
                                    </Grid>
                                </Grid>

```

It displays the theme background but not the syntax highlighting. I tried two of these styles from prism Any help? 

Screenshot available [here](https://drive.google.com/file/d/1RSOPyilaZHra00XFTOeZp5lhnxzENyOx/view?usp=sharing)

**Comment by conorhastings** [comment]
@kushalmahajan in reference to issue 130, that answer was correct at that time, the library has undergone major versions since then, meaning that all examples in previous issues won't work.

As to your question about not highlighting, that is due to javascript being setting as the language, while your codeblock is jsx, jsx is not valid javascript, you need to use jsx or tsx as the language to properly highlight that

examples here: https://codesandbox.io/s/6z2k2okr7w

**Comment by kushalmahajan** [comment]
Yes it does. Earlier I was trying with jsx or tsx to switch and see. At that time I wasn't using prism  which I learnt later while exploring to use for jsx/tsx files. Sorry for the hassle!
