### ISSUE TITLE
code folding

### ISSUE THREAD

**Issue by atambo** [conorhastings/react-syntax-highlighter#48]
Is there any good way to implement json/html code folding with react-syntax-highlighter?

**Comment by conorhastings** [comment]
not right now but theoretcally possible to extend line number functionality to allow this

**Comment by atambo** [comment]
Do you mean by adding a new prop that would like add a class to a wrapper around the code block? The only structure I see in the markup is the span that wraps each line, so I'd need like a div to wrap around each "block" of code or something. Not sure what lowlight gives you in terms of detecting things like blocks of code like functions or objects etc.

**Comment by conorhastings** [comment]
I'll look into knowledge of code block and try to get back to this over the weekend. Love the idea though

**Comment by conorhastings** [comment]
Lowlight uses highlight.js under the hood, and since highlight.js doesn't support the neccesary primitives to makes this possible, ie we're returned things like the span to wrap around a `const` and another span to wrap around `variableName` but not anything that denotes blocks it would be hard to make this happen, going to close for now pending a breakthrough in highlight.js
